# Generated by Django 5.2.8 on 2026-01-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0015_alter_structure_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='address',
        ),
        migrations.AddField(
            model_name='structure',
            name='address_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='address(en)'),
        ),
        migrations.AddField(
            model_name='structure',
            name='address_kg',
            field=models.CharField(blank=True, max_length=500, verbose_name='address(kg)'),
        ),
        migrations.AddField(
            model_name='structure',
            name='address_ru',
            field=models.CharField(blank=True, max_length=500, verbose_name='address(ru)'),
        ),
    ]
