# Generated by Django 5.2.8 on 2026-01-27 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0016_remove_structure_address_structure_address_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kg', models.CharField(max_length=255, unique=True, verbose_name='название на кыргызском')),
                ('name_en', models.CharField(max_length=255, unique=True, verbose_name='название на английском')),
                ('name_ru', models.CharField(max_length=255, unique=True, verbose_name='название на русском')),
            ],
            options={
                'verbose_name': 'категория для структур',
                'verbose_name_plural': 'категории для структур',
            },
        ),
        migrations.AddField(
            model_name='structure',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about_us.categorystructure', verbose_name='категория'),
        ),
    ]
