# Generated by Django 5.2.8 on 2026-01-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0017_categorystructure_structure_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Скрыть'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='address_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='адрес на английском'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='address_kg',
            field=models.CharField(blank=True, max_length=500, verbose_name='адрес на кыргызском'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='address_ru',
            field=models.CharField(blank=True, max_length=500, verbose_name='адрес на русском '),
        ),
    ]
