# Generated by Django 5.2.8 on 2026-01-27 11:08

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='about_company_en',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='about_company_kg',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='about_company_ru',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='about_corporation_en',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='about_corporation_kg',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='about_corporation_ru',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='achievements_en',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='achievements_kg',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='achievements_ru',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='features_en',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='features_kg',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='features_ru',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='founded_year',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='otrasl_en',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='otrasl_kg',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='otrasl_ru',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='partnership_status_en',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='partnership_status_kg',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='partnership_status_ru',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='shtab_kvartira_en',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='shtab_kvartira_kg',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='shtab_kvartira_ru',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='ulugi_en',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='ulugi_kg',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='ulugi_ru',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='website',
        ),
        migrations.AddField(
            model_name='partner',
            name='coord1',
            field=models.CharField(default=1, max_length=55, verbose_name='координаты ширины(LAT)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='coord2',
            field=models.CharField(default=1, max_length=55, verbose_name='координаты долготы(LMG)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description (EN)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description_kg',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description (KG)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description (RU)'),
        ),
    ]
