# Generated by Django 5.2.8 on 2026-01-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_remove_partner_about_company_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='coord1',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='координаты ширины(LAT)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='coord2',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='координаты долготы(LMG)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partners/logos/', verbose_name='Логотип'),
        ),
    ]
