# Generated by Django 5.2.8 on 2026-01-31 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_alter_partner_coord1_alter_partner_coord2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Название (EN)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название (RU)')),
                ('title_kg', models.CharField(max_length=255, verbose_name='Название (KG)')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок (EN)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (RU)')),
                ('title_kg', models.CharField(max_length=255, verbose_name='Заголовок (KG)')),
                ('short_description_en', models.TextField(blank=True, verbose_name='Краткое описание (EN)')),
                ('short_description_ru', models.TextField(blank=True, verbose_name='Краткое описание (RU)')),
                ('short_description_kg', models.TextField(blank=True, verbose_name='Краткое описание (KG)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (EN)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (RU)')),
                ('description_kg', models.TextField(blank=True, verbose_name='Описание (KG)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('published_at', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, help_text='Рекомендуемый размер: (16:9)', null=True, upload_to='news/', verbose_name='Изображение')),
                ('cropping', models.CharField(blank=True, help_text='Координаты обрезки изображения (JSON формат)', max_length=255, null=True, verbose_name='Обрезка изображения')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='partners.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
            },
        ),
        migrations.CreateModel(
            name='ProjectsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/photos/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения фото', verbose_name='Порядок')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='partners.projects', verbose_name='проект')),
            ],
            options={
                'verbose_name': 'Фото проекта',
                'verbose_name_plural': 'Фото проектов',
                'ordering': ['order', 'id'],
            },
        ),
    ]
