# Generated by Django 5.2.8 on 2025-12-22 04:55

from django.db import migrations, models


def add_cropping_column(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute(
            "ALTER TABLE presscentre_news ADD COLUMN IF NOT EXISTS cropping VARCHAR(255) NULL;"
        )
    elif vendor == "sqlite":
        return
    else:
        schema_editor.execute(
            "ALTER TABLE presscentre_news ADD COLUMN cropping VARCHAR(255);"
        )


def remove_cropping_column(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute(
            "ALTER TABLE presscentre_news DROP COLUMN IF EXISTS cropping;"
        )
    elif vendor == "sqlite":
        return
    else:
        schema_editor.execute("ALTER TABLE presscentre_news DROP COLUMN cropping;")


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0012_publication_gallery_alter_news_image'),
    ]

    operations = [
        migrations.RunPython(add_cropping_column, remove_cropping_column),
    ]
