# Generated by Django 5.2.8 on 2025-12-27 05:58

from django.db import migrations, models


def ensure_cropping_column(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute(
            "ALTER TABLE presscentre_news ADD COLUMN IF NOT EXISTS cropping VARCHAR(255) NULL;"
        )
    elif vendor == "sqlite":
        return
    else:
        schema_editor.execute(
            "ALTER TABLE presscentre_news ADD COLUMN cropping VARCHAR(255);"
        )


def drop_cropping_column(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute(
            "ALTER TABLE presscentre_news DROP COLUMN IF EXISTS cropping;"
        )
    elif vendor == "sqlite":
        return
    else:
        schema_editor.execute("ALTER TABLE presscentre_news DROP COLUMN cropping;")


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0018_remove_publication_category'),
    ]

    operations = [
        migrations.RunPython(ensure_cropping_column, drop_cropping_column),
    ]
