# Generated by Django 5.2.8 on 2026-01-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0019_news_cropping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-created_at'], 'verbose_name': 'СМИ о нас', 'verbose_name_plural': 'СМИ о нас'},
        ),
        migrations.AddField(
            model_name='news',
            name='cropping',
            field=models.CharField(blank=True, help_text='Координаты обрезки изображения (JSON формат)', max_length=255, null=True, verbose_name='Обрезка изображения'),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Короткое описание (EN)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_kg',
            field=models.TextField(blank=True, verbose_name='Короткое описание (KG)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Короткое описание (RU)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='publications/', verbose_name='Фото'),
        ),
    ]
