# Generated by Django 5.2.8 on 2026-01-23 02:51

from django.db import migrations, models


def add_cropping_column_if_missing(apps, schema_editor):
    News = apps.get_model('presscentre', 'News')
    table = News._meta.db_table
    column_name = 'cropping'

    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            column.name for column in schema_editor.connection.introspection.get_table_description(cursor, table)
        }

    if column_name in existing_columns:
        return

    field = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        verbose_name='Обрезка изображения',
        help_text='Координаты обрезки изображения (JSON формат)',
    )
    field.set_attributes_from_name(column_name)
    schema_editor.add_field(News, field)


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0019_news_cropping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-created_at'], 'verbose_name': 'СМИ о нас', 'verbose_name_plural': 'СМИ о нас'},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_cropping_column_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='news',
                    name='cropping',
                    field=models.CharField(
                        blank=True,
                        help_text='Координаты обрезки изображения (JSON формат)',
                        max_length=255,
                        null=True,
                        verbose_name='Обрезка изображения',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Короткое описание (EN)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_kg',
            field=models.TextField(blank=True, verbose_name='Короткое описание (KG)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Короткое описание (RU)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='publications/', verbose_name='Фото'),
        ),
    ]
